apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
data:
  GRPC_PORT: {{ .Values.config.GRPC_PORT | quote }}
  REDIS_ADDR: {{ .Values.config.REDIS_ADDR | quote }}
  REDIS_DB: {{ .Values.config.REDIS_DB | quote }}
  CACHE_TTL: {{ .Values.config.CACHE_TTL | quote }}
