apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
            - containerPort: {{ .Values.metrics.port }}
          envFrom:
            - configMapRef:
                name: chat-service-config
            - secretRef:
                name: chat-service-secret
