apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9101"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chat-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: metrics
      port: 9101
      targetPort: 9101
