apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chat-service
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
