apiVersion: v2
name: platform
description: Umbrella chart for mgz platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: api-gateway
    version: 0.1.0
    repository: "file://../services/api-gateway"

  - name: auth-service
    version: 0.1.0
    repository: "file://../services/auth-service"

  - name: chat-service
    version: 0.1.0
    repository: "file://../services/chat-service"

  - name: user-service
    version: 0.1.0
    repository: "file://../services/user-service"

  - name: postgresql
    version: 0.1.0
    repository: "file://../infra/postgresql"

  - name: redis
    version: 0.1.0
    repository: "file://../infra/redis"

  - name: minio
    version: 0.1.0
    repository: "file://../infra/minio"

#  - name: kube-prometheus-stack
#    version: 61.3.2
#    repository: "https://prometheus-community.github.io/helm-charts"
#    condition: monitoring.enabled
