api-gateway: {}
auth-service: {}
chat-service: {}
user-service: {}
postgresql: {}
redis: {}
minio: {}

monitoring:
  enabled: true

kube-prometheus-stack:
  grafana:
    enabled: true
  alertmanager:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      retention: 7d
