apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SERVER_PORT: {{ .Values.config.SERVER_PORT | quote }}
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.config.REDIS_URL | quote }}
  JWT_ACCESS_TTL_MINUTES: {{ .Values.config.JWT_ACCESS_TTL_MINUTES | quote }}
  JWT_REFRESH_TTL_DAYS: {{ .Values.config.JWT_REFRESH_TTL_DAYS | quote }}
