apiVersion: v1
kind: Service
metadata:
  name: auth-service  
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8081"  
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
