apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.service.metricsPort | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.container.metricsPort }}
      protocol: TCP
