apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
