replicaCount: 1

image:
  repository: your-dockerhub-or-registry/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

container:
  port: 8080

config:
  GATEWAY_PORT: "8080"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  CHAT_SERVICE_URL: "chat-service:50051"
  USER_SERVICE_URL: "user-service:50052"

secret:
  JWT_SECRET: "change-me"
