apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  GATEWAY_PORT: {{ .Values.config.GATEWAY_PORT | quote }}
  AUTH_SERVICE_URL: {{ .Values.config.AUTH_SERVICE_URL | quote }}
  CHAT_SERVICE_URL: {{ .Values.config.CHAT_SERVICE_URL | quote }}
  USER_SERVICE_URL: {{ .Values.config.USER_SERVICE_URL | quote }}
