apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: {{ .Values.service.metricsPort | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
