image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

container:
  port: 5432

persistence:
  enabled: true
  size: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""

config:
  POSTGRES_DB: auth

secret:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
