apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: "{{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}"
          imagePullPolicy: {{ .Values.mcImage.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - >
              sleep 5;
              mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD";
              mc mb myminio/{{ .Values.config.bucketName }} --ignore-existing;
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
