apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: {{ .Values.service.type }}
  selector:
    app: minio
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
